export const FETCH_LOADING = 'FETCH_LOADING';
export const GET_APPROVED_LOANS = 'GET_APPROVED_LOANS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const GET_APPROVED_LOANS_SUCCESS = 'GET_APPROVED_LOANS_SUCCESS';
export const GET_LOAN_APPLICATIONS_SUCCESS = 'GET_LOAN_APPLICATIONS_SUCCESS';

//loan detail
export const GET_LOAN_DETAIL = "GET_LOAN_DETAIL";

//colleterals
export const GET_LOAN_COLLETERALS = "GET_LOAN_COLLETERALS";
export const GET_COLLETERAL_LIST_SUCCESS = "GET_COLLETERAL_LIST_SUCCESS";

//budget
export const GET_BUDGET_LIST = "GET_BUDGET_LIST"
export const GET_BUDGET_LIST_SUCCESS = "GET_BUDGET_LIST_SUCCESS";


